{{- if .Values.bundle.enabled }}
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ .Values.bundle.name }}  # The bundle name will also be used for the target
spec:
  sources:
    - useDefaultCAs: true
    # A Secret in the "trust" namespace; see "Trust Namespace" below for further details
{{- range .Values.caClusterIssuers }}
    - secret:
        name: {{ .name }}
        key: "tls.crt"
{{- end }}
{{- range .Values.selfsignedClusterIssuers }}
    - secret:
        name: {{ .name }}
        key: "tls.crt"
{{- end }}
  target:
    configMap:
      key: "root-certs.pem"
    namespaceSelector:
{{- toYaml .Values.bundle.namespaceSelector | nindent 6 }}
{{- end }}
