
{{- range .Values.selfsignedClusterIssuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}-self
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: {{ .name }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .name }}-self
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  ca:
    secretName: {{ .name }}
{{- end}}
