---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  {{- range  .Values.ipRanges }}
  - {{ .first }}-{{ .last }}
  {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-pool
  namespace: {{ .Release.Namespace }}
