
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubedp
  namespace: flux-system
spec:
  interval: 1m    # TODO: Set to 24h after setup
  url: https://kubedp.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kad-controller
  namespace: flux-system
spec:
  interval: 1m
  serviceAccountName: kustomize-controller
  targetNamespace: flux-system
  storageNamespace: flux-system
  releaseName: kad-controller
  timeout: 2m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: kubedp
        namespace: flux-system
      reconcileStrategy: Revision
      chart: kad-controller
      version: "0.2.0-a1"
      interval: 1m
  values:
    config:
      primarySources:
        - name: flux-system
          namespace: flux-system
          kadFiles:
            - clusters/context.yaml
            - clusters/kind/context.yaml
            - clusters/kind/kind/context.yaml
            - clusters/kind/kind/deployments
            - components
            - templates.yaml
      sweepPeriod: 2m # TODO: Set to 1h after setup
    logger:
      mode: dev
      level: info
    image:
      tag: 0.2.0.snapshot
      pullPolicy: Always

